### PR TITLE
Change order of menu sections

### PR DESCRIPTION
**Pull request by chantal-kelm**
### Description

Show the dashboard management section first and then the indexer management section.

## Evidence

Captura de pantalla 2024-10-18 a la(s) 5 32 07 p  m

### Check List

- [x] All tests pass
  - [ ] `yarn test:jest`
  - [ ] `yarn test:jest_integration`
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [x] Update [CHANGELOG.md](./../CHANGELOG.md)
- [x] Commits are signed per the DCO using --signoff

### CODE REVIEW

**Comment by Desvelao** [comment]
The category order of `Indexer management` should be changed here too: https://github.com/wazuh/wazuh-dashboard/blob/7069-change-order-of-menu-sections/dev-tools/build-packages/base/generate_base.sh#L170

**Review by yenienserrano — APPROVED** [review]
LGTM 

image

**Comment by chantal-kelm** [comment]
> The category order of `Indexer management` should be changed here too: https://github.com/wazuh/wazuh-dashboard/blob/7069-change-order-of-menu-sections/dev-tools/build-packages/base/generate_base.sh#L170

Fixed in commit [d424cae](https://github.com/wazuh/wazuh-dashboard/pull/372/commits/d424caec792cb45abec4329ec6e392d85564e524)

**Review by asteriscos — APPROVED** [review]
CR: :green_circle: 
Test: :green_circle: 

image

**Pull request merged**
